=== svn2github/ngene/trunk/bin/media/shaderConfig.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:element name="root">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="script" minOccurs="0" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:attribute name="language" type="xsd:string" use="required" />
            <xsd:attribute name="file" type="xsd:string" use="required" />
          </xsd:complexType>
        </xsd:element>
        <xsd:element name="data_type" minOccurs="0" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:attribute name="name" type="xsd:string" use="required" />
            <xsd:attribute name="values_count" type="xsd:integer" use="required" />
            <xsd:attribute name="base_type" type="BaseTypes" use="optional" />
          </xsd:complexType>
        </xsd:element>
        <xsd:element name="semantic" minOccurs="0" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:attribute name="name" type="xsd:string" use="required" />
            <xsd:attribute name="data_type" type="xsd:string" use="required" />
            <xsd:attribute name="function" type="xsd:string" use="optional" />
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:simpleType name="BaseTypes">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="FLOAT" />
      <xsd:enumeration value="INTEGER" />
      <xsd:enumeration value="BOOLEAN" />
    </xsd:restriction>
  </xsd:simpleType>
</xsd:schema>

=== svn2github/ngene/trunk/bin/media/ShaderConfig.xml
<?xml version="1.0"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="shaderConfig.xsd">
	<script language="lua" file="semanticFunctions.lua"/>
	
	<data_type name="float" values_count = "1" base_type="FLOAT" />
  <data_type name="float2" values_count = "2" base_type="FLOAT" />
	<data_type name="float3" values_count = "3" base_type="FLOAT" />
	<data_type name="float4" values_count = "4" base_type="FLOAT" />
  
  <data_type name="matrix2" values_count = "4" base_type="FLOAT" />
  <data_type name="matrix3" values_count = "9" base_type="FLOAT" />
	<data_type name="matrix4" values_count = "16" base_type="FLOAT" />

  <data_type name="int" values_count = "1" base_type="INTEGER" />
  <data_type name="int2" values_count = "2" base_type="INTEGER" />
  <data_type name="int3" values_count = "3" base_type="INTEGER" />
  <data_type name="int4" values_count = "4" base_type="INTEGER" />

  <data_type name="bool" values_count = "1" base_type="BOOLEAN" />
  <data_type name="bool2" values_count = "2" base_type="BOOLEAN" />
  <data_type name="bool3" values_count = "3" base_type="BOOLEAN" />
  <data_type name="bool4" values_count = "4" base_type="BOOLEAN" />
	
	<semantic name="WorldViewProj" data_type="matrix4"/>
	<semantic name="ViewProj" data_type="matrix4"/>
	<semantic name="ViewInverse" data_type="matrix4"/>
	<semantic name="ViewInverseTranspose" data_type="matrix4"/>
	<semantic name="World" data_type="matrix4"/>
	<semantic name="View" data_type="matrix4"/>
	<semantic name="WorldView" data_type="matrix4"/>
	<semantic name="Proj" data_type="matrix4"/>
	<semantic name="ProjInverse" data_type="matrix4"/>
	
	<semantic name="Camera" data_type="matrix4"/>
	<semantic name="CameraInverse" data_type="matrix4"/>
	<semantic name="CameraProjection" data_type="matrix4" function="cameraProjection"/>
	<semantic name="CameraViewProjection" data_type="matrix4" function="cameraViewProjection"/>
	<semantic name="CameraForward" data_type="float3" function="cameraForward"/>
	<semantic name="EyePosition" data_type="float3"/>
	
	<semantic name="LightDirection" data_type="float3"/>
	<semantic name="LightPosition" data_type="float3"/>
	<semantic name="LightIntensity" data_type="float"/>
	<semantic name="LightColour" data_type="float4"/>
	<semantic name="LightRadius" data_type="float3"/>
	<semantic name="LightFov" data_type="float"/>
	<semantic name="LightSpotExponent" data_type="float"/>
	<semantic name="LightConstantAttenuation" data_type="float"/>
	<semantic name="LightLinearAttenuation" data_type="float"/>
	<semantic name="LightQuadraticAttenuation" data_type="float"/>

	<semantic name="ShadowDensity" data_type="float"/>
	
	<semantic name="NearPlane" data_type="float"/>
	<semantic name="FarPlane" data_type="float"/>
	
	<semantic name="InvTanHalfFov" data_type="float"/>
	<semantic name="Aspect" data_type="float"/>
	<semantic name="PixelSize" data_type="float2"/>
	
	<semantic name="Ambient" data_type="float4"/>
	<semantic name="Diffuse" data_type="float4"/>
	<semantic name="Emissive" data_type="float"/>
	
	<semantic name="Time" data_type="float"/>
</root>
